version: '3.1'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  quote-dictionary:
    build: ./
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - "db:database"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-1:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

