spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name:
      org.postgresql.Driver
    url: jdbc:postgresql://db-1:5432/postgres
    username: postgres
    password: root
  flyway:
    schemas: public
    out-of-order: true
    enabled: true
    user: postgres
    password: root
    default-schema: public

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate